# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  test:
    cmds:
      - uv run pytest

  watch-tests:
    cmds:
      - find tests mcp_client -type f -not -path '*/__pycache__/*' | entr uv run pytest
